rm (list = ls(all=TRUE))
graphics.off()
install.packages("readxl")
install.packages("boot")
install.packages("pastecs")
install.packages("xlsx")
library(readxl)
CTO <- read_excel("C:/Users/Mihan/Dropbox/DataCamp/R/Network_Analysis/CTO.xlsx")
rawdata <- read_excel("C:/Users/Mihan/Dropbox/Mardi Meetings/Meeting 22/Testing/Important_codes/rawdata.xlsx")
library(boot)
library(pastecs)
library(xlsx)
CPNEW <- read_excel("C:/Users/Mihan/Dropbox/DataCamp/R/Network_Analysis/CPNEW.xlsx")
Z <- read_excel("C:/Users/Mihan/Dropbox/Mardi Meetings/Meeting 22/Testing/Important_codes/Z.xlsx")
dst<-stat.desc(rawdata)
dst2<-stat.desc(CPNEW)
dst3<-stat.desc(Z)

